import { getCliClient } from "sanity/cli";

const LEVEL_N5_ID = "c68eb6ad-8afb-4e7a-8ce9-2d0a1dac0357";

const vocabLessonsBatch2: any[] = [
  {
    _id: "n5-vocab-lesson-05",
    _type: "lesson",
    title: "5. Tempat & Posisi Benda",
    slug: { _type: "slug", current: "tempat-dan-posisi-n5" },
    category: "vocabulary",
    orderNumber: 5,
    is_published: true,
    summary:
      "Kosakata seputar ruangan di rumah, bangunan di kota, serta arah dan posisi letak benda.",
    level: { _ref: LEVEL_N5_ID, _type: "reference" },
    content: [
      {
        _key: "b1",
        _type: "block",
        style: "h2",
        children: [{ _key: "s1", _type: "span", text: "Ruangan & Rumah" }],
      },
      {
        _key: "ex1",
        _type: "exampleSentence",
        jp: "部屋",
        furigana: "Heya",
        id: "Kamar / Ruangan",
      },
      {
        _key: "ex2",
        _type: "exampleSentence",
        jp: "台所",
        furigana: "Daidokoro",
        id: "Dapur",
      },
      {
        _key: "ex3",
        _type: "exampleSentence",
        jp: "お風呂",
        furigana: "Ofuro",
        id: "Kamar mandi / Bak mandi",
      },
      {
        _key: "ex4",
        _type: "exampleSentence",
        jp: "階段",
        furigana: "Kaidan",
        id: "Tangga",
      },

      {
        _key: "b2",
        _type: "block",
        style: "h2",
        children: [{ _key: "s2", _type: "span", text: "Bangunan & Kota" }],
      },
      {
        _key: "ex5",
        _type: "exampleSentence",
        jp: "駅",
        furigana: "Eki",
        id: "Stasiun",
      },
      {
        _key: "ex6",
        _type: "exampleSentence",
        jp: "空港",
        furigana: "Kuukoo",
        id: "Bandara",
      },
      {
        _key: "ex7",
        _type: "exampleSentence",
        jp: "公園",
        furigana: "Kooen",
        id: "Taman",
      },
      {
        _key: "ex8",
        _type: "exampleSentence",
        jp: "病院",
        furigana: "Byooin",
        id: "Rumah sakit",
      },
      {
        _key: "ex9",
        _type: "exampleSentence",
        jp: "食堂",
        furigana: "Shokudoo",
        id: "Kantin / Ruang makan",
      },

      {
        _key: "b3",
        _type: "block",
        style: "h2",
        children: [{ _key: "s3", _type: "span", text: "Posisi & Arah" }],
      },
      {
        _key: "ex10",
        _type: "exampleSentence",
        jp: "上",
        furigana: "Ue",
        id: "Atas",
      },
      {
        _key: "ex11",
        _type: "exampleSentence",
        jp: "下",
        furigana: "Shita",
        id: "Bawah",
      },
      {
        _key: "ex12",
        _type: "exampleSentence",
        jp: "中",
        furigana: "Naka",
        id: "Dalam",
      },
      {
        _key: "ex13",
        _type: "exampleSentence",
        jp: "前",
        furigana: "Mae",
        id: "Depan",
      },
      {
        _key: "ex14",
        _type: "exampleSentence",
        jp: "後ろ",
        furigana: "Ushiro",
        id: "Belakang",
      },
      {
        _key: "ex15",
        _type: "exampleSentence",
        jp: "横",
        furigana: "Yoko",
        id: "Samping",
      },
    ],
  },
  {
    _id: "n5-vocab-lesson-06",
    _type: "lesson",
    title: "6. Kata Kerja Harian & Hobi",
    slug: { _type: "slug", current: "kata-kerja-harian-hobi-n5" },
    category: "vocabulary",
    orderNumber: 6,
    is_published: true,
    summary:
      "Daftar kata kerja (Verbs) paling penting untuk aktivitas sehari-hari, transportasi, dan hobi.",
    level: { _ref: LEVEL_N5_ID, _type: "reference" },
    content: [
      {
        _key: "b1",
        _type: "block",
        style: "h2",
        children: [{ _key: "s1", _type: "span", text: "Aktivitas Dasar" }],
      },
      {
        _key: "ex1",
        _type: "exampleSentence",
        jp: "起きます",
        furigana: "Okimasu",
        id: "Bangun tidur",
      },
      {
        _key: "ex2",
        _type: "exampleSentence",
        jp: "寝ます",
        furigana: "Nemasu",
        id: "Tidur",
      },
      {
        _key: "ex3",
        _type: "exampleSentence",
        jp: "食べます",
        furigana: "Tabemasu",
        id: "Makan",
      },
      {
        _key: "ex4",
        _type: "exampleSentence",
        jp: "飲みます",
        furigana: "Nomimasu",
        id: "Minum",
      },
      {
        _key: "ex5",
        _type: "exampleSentence",
        jp: "買います",
        furigana: "Kaimasu",
        id: "Membeli",
      },

      {
        _key: "b2",
        _type: "block",
        style: "h2",
        children: [{ _key: "s2", _type: "span", text: "Pergerakan" }],
      },
      {
        _key: "ex6",
        _type: "exampleSentence",
        jp: "行きます",
        furigana: "Ikimasu",
        id: "Pergi",
      },
      {
        _key: "ex7",
        _type: "exampleSentence",
        jp: "来ます",
        furigana: "Kimasu",
        id: "Datang",
      },
      {
        _key: "ex8",
        _type: "exampleSentence",
        jp: "帰ります",
        furigana: "Kaerimasu",
        id: "Pulang",
      },
      {
        _key: "ex9",
        _type: "exampleSentence",
        jp: "乗ります",
        furigana: "Norimasu",
        id: "Naik (kendaraan)",
      },
      {
        _key: "ex10",
        _type: "exampleSentence",
        jp: "降ります",
        furigana: "Orimasu",
        id: "Turun (dari kendaraan)",
      },

      {
        _key: "b3",
        _type: "block",
        style: "h2",
        children: [{ _key: "s3", _type: "span", text: "Hobi & Informasi" }],
      },
      {
        _key: "ex11",
        _type: "exampleSentence",
        jp: "見ます",
        furigana: "Mimasu",
        id: "Melihat / Menonton",
      },
      {
        _key: "ex12",
        _type: "exampleSentence",
        jp: "聞きます",
        furigana: "Kikimasu",
        id: "Mendengar",
      },
      {
        _key: "ex13",
        _type: "exampleSentence",
        jp: "読みます",
        furigana: "Yomimasu",
        id: "Membaca",
      },
      {
        _key: "ex14",
        _type: "exampleSentence",
        jp: "話します",
        furigana: "Hanashimasu",
        id: "Berbicara",
      },
      {
        _key: "ex15",
        _type: "exampleSentence",
        jp: "勉強します",
        furigana: "Benkyoo shimasu",
        id: "Belajar",
      },
    ],
  },
  {
    _id: "n5-vocab-lesson-07",
    _type: "lesson",
    title: "7. Kalender & Waktu",
    slug: { _type: "slug", current: "kalender-dan-waktu-n5" },
    category: "vocabulary",
    orderNumber: 7,
    is_published: true,
    summary:
      "Cara menyebutkan jam, hari dalam seminggu, serta nama-nama bulan.",
    level: { _ref: LEVEL_N5_ID, _type: "reference" },
    content: [
      {
        _key: "b1",
        _type: "block",
        style: "h2",
        children: [{ _key: "s1", _type: "span", text: "Keterangan Waktu" }],
      },
      {
        _key: "ex1",
        _type: "exampleSentence",
        jp: "今",
        furigana: "Ima",
        id: "Sekarang",
      },
      {
        _key: "ex2",
        _type: "exampleSentence",
        jp: "朝",
        furigana: "Asa",
        id: "Pagi",
      },
      {
        _key: "ex3",
        _type: "exampleSentence",
        jp: "昼",
        furigana: "Hiru",
        id: "Siang",
      },
      {
        _key: "ex4",
        _type: "exampleSentence",
        jp: "夜",
        furigana: "Yoru",
        id: "Malam",
      },
      {
        _key: "ex5",
        _type: "exampleSentence",
        jp: "今日",
        furigana: "Kyoo",
        id: "Hari ini",
      },
      {
        _key: "ex6",
        _type: "exampleSentence",
        jp: "明日",
        furigana: "Ashita",
        id: "Besok",
      },
      {
        _key: "ex7",
        _type: "exampleSentence",
        jp: "昨日",
        furigana: "Kinoo",
        id: "Kemarin",
      },

      {
        _key: "b2",
        _type: "block",
        style: "h2",
        children: [{ _key: "s2", _type: "span", text: "Hari (曜日)" }],
      },
      {
        _key: "ex8",
        _type: "exampleSentence",
        jp: "月曜日",
        furigana: "Getsuyoobi",
        id: "Senin",
      },
      {
        _key: "ex9",
        _type: "exampleSentence",
        jp: "火曜日",
        furigana: "Kayoobi",
        id: "Selasa",
      },
      {
        _key: "ex10",
        _type: "exampleSentence",
        jp: "水曜日",
        furigana: "Suiyoobi",
        id: "Rabu",
      },
      {
        _key: "ex11",
        _type: "exampleSentence",
        jp: "木曜日",
        furigana: "Mokuyoobi",
        id: "Kamis",
      },
      {
        _key: "ex12",
        _type: "exampleSentence",
        jp: "金曜日",
        furigana: "Kinyoobi",
        id: "Jumat",
      },
      {
        _key: "ex13",
        _type: "exampleSentence",
        jp: "土曜日",
        furigana: "Doyoobi",
        id: "Sabtu",
      },
      {
        _key: "ex14",
        _type: "exampleSentence",
        jp: "日曜日",
        furigana: "Nichiyoobi",
        id: "Minggu",
      },

      {
        _key: "b3",
        _type: "block",
        style: "h2",
        children: [{ _key: "s3", _type: "span", text: "Bulan (月)" }],
      },
      {
        _key: "b4",
        _type: "block",
        style: "normal",
        children: [
          {
            _key: "s4",
            _type: "span",
            text: "Bulan dalam bahasa Jepang sangat mudah, cukup Angka + Gatsu (月).",
          },
        ],
      },
      {
        _key: "ex15",
        _type: "exampleSentence",
        jp: "１月",
        furigana: "Ichigatsu",
        id: "Januari",
      },
      {
        _key: "ex16",
        _type: "exampleSentence",
        jp: "４月",
        furigana: "Shigatsu",
        id: "April (Bukan Yongatsu)",
      },
      {
        _key: "ex17",
        _type: "exampleSentence",
        jp: "７月",
        furigana: "Shichigatsu",
        id: "Juli (Bukan Nanagatsu)",
      },
      {
        _key: "ex18",
        _type: "exampleSentence",
        jp: "９月",
        furigana: "Kugatsu",
        id: "September (Bukan Kyuugatsu)",
      },
    ],
  },
  {
    _id: "n5-vocab-lesson-08",
    _type: "lesson",
    title: "8. Belanja, Uang & Barang Pribadi",
    slug: { _type: "slug", current: "belanja-uang-barang-n5" },
    category: "vocabulary",
    orderNumber: 8,
    is_published: true,
    summary:
      "Menyebutkan nominal uang (Yen), pakaian, dan barang-barang yang sering digunakan sehari-hari.",
    level: { _ref: LEVEL_N5_ID, _type: "reference" },
    content: [
      {
        _key: "b1",
        _type: "block",
        style: "h2",
        children: [{ _key: "s1", _type: "span", text: "Uang & Harga" }],
      },
      {
        _key: "ex1",
        _type: "exampleSentence",
        jp: "百",
        furigana: "Hyaku",
        id: "100",
      },
      {
        _key: "ex2",
        _type: "exampleSentence",
        jp: "千",
        furigana: "Sen",
        id: "1.000",
      },
      {
        _key: "ex3",
        _type: "exampleSentence",
        jp: "一万",
        furigana: "Ichiman",
        id: "10.000",
      },
      {
        _key: "ex4",
        _type: "exampleSentence",
        jp: "いくら",
        furigana: "Ikura",
        id: "Berapa harganya?",
      },
      {
        _key: "ex5",
        _type: "exampleSentence",
        jp: "半額",
        furigana: "Hangaku",
        id: "Setengah harga (Diskon 50%)",
      },

      {
        _key: "b2",
        _type: "block",
        style: "h2",
        children: [{ _key: "s2", _type: "span", text: "Barang & Pakaian" }],
      },
      {
        _key: "ex6",
        _type: "exampleSentence",
        jp: "服",
        furigana: "Fuku",
        id: "Pakaian",
      },
      {
        _key: "ex7",
        _type: "exampleSentence",
        jp: "靴",
        furigana: "Kutsu",
        id: "Sepatu",
      },
      {
        _key: "ex8",
        _type: "exampleSentence",
        jp: "傘",
        furigana: "Kasa",
        id: "Payung",
      },
      {
        _key: "ex9",
        _type: "exampleSentence",
        jp: "かばん",
        furigana: "Kaban",
        id: "Tas",
      },
      {
        _key: "ex10",
        _type: "exampleSentence",
        jp: "時計",
        furigana: "Tokei",
        id: "Jam (tangan/dinding)",
      },

      {
        _key: "b3",
        _type: "block",
        style: "h2",
        children: [{ _key: "s3", _type: "span", text: "Alat Tulis & Kantor" }],
      },
      {
        _key: "ex11",
        _type: "exampleSentence",
        jp: "ペン",
        furigana: "Pen",
        id: "Pena",
      },
      {
        _key: "ex12",
        _type: "exampleSentence",
        jp: "鉛筆",
        furigana: "Enpitsu",
        id: "Pensil",
      },
      {
        _key: "ex13",
        _type: "exampleSentence",
        jp: "消しゴム",
        furigana: "Keshigomu",
        id: "Penghapus",
      },
      {
        _key: "ex14",
        _type: "exampleSentence",
        jp: "はさみ",
        furigana: "Hasami",
        id: "Gunting",
      },
      {
        _key: "ex15",
        _type: "exampleSentence",
        jp: "パソコン",
        furigana: "Pasokon",
        id: "Komputer Pribadi (PC)",
      },
    ],
  },
  {
    _id: "n5-vocab-lesson-09",
    _type: "lesson",
    title: "9. Kata Sifat (Karakteristik & Perasaan)",
    slug: { _type: "slug", current: "kata-sifat-n5" },
    category: "vocabulary",
    orderNumber: 9,
    is_published: true,
    summary:
      "Kata sifat dasar untuk mendeskripsikan benda (besar/kecil) dan perasaan/kondisi (senang/sibuk).",
    level: { _ref: LEVEL_N5_ID, _type: "reference" },
    content: [
      {
        _key: "b1",
        _type: "block",
        style: "h2",
        children: [
          { _key: "s1", _type: "span", text: "Kata Sifat - I (い形容詞)" },
        ],
      },
      {
        _key: "ex1",
        _type: "exampleSentence",
        jp: "大きい",
        furigana: "Ookii",
        id: "Besar",
      },
      {
        _key: "ex2",
        _type: "exampleSentence",
        jp: "小さい",
        furigana: "Chiisai",
        id: "Kecil",
      },
      {
        _key: "ex3",
        _type: "exampleSentence",
        jp: "新しい",
        furigana: "Atarashii",
        id: "Baru",
      },
      {
        _key: "ex4",
        _type: "exampleSentence",
        jp: "古い",
        furigana: "Furui",
        id: "Lama / Tua",
      },
      {
        _key: "ex5",
        _type: "exampleSentence",
        jp: "高い",
        furigana: "Takai",
        id: "Tinggi / Mahal",
      },
      {
        _key: "ex6",
        _type: "exampleSentence",
        jp: "安い",
        furigana: "Yasui",
        id: "Murah",
      },
      {
        _key: "ex7",
        _type: "exampleSentence",
        jp: "おいしい",
        furigana: "Oishii",
        id: "Enak",
      },
      {
        _key: "ex8",
        _type: "exampleSentence",
        jp: "楽しい",
        furigana: "Tanoshii",
        id: "Menyenangkan",
      },

      {
        _key: "b2",
        _type: "block",
        style: "h2",
        children: [
          { _key: "s2", _type: "span", text: "Kata Sifat - Na (な形容詞)" },
        ],
      },
      {
        _key: "ex9",
        _type: "exampleSentence",
        jp: "きれい",
        furigana: "Kirei",
        id: "Cantik / Bersih",
      },
      {
        _key: "ex10",
        _type: "exampleSentence",
        jp: "静か",
        furigana: "Shizuka",
        id: "Sepi / Tenang",
      },
      {
        _key: "ex11",
        _type: "exampleSentence",
        jp: "にぎやか",
        furigana: "Nigiyaka",
        id: "Ramai",
      },
      {
        _key: "ex12",
        _type: "exampleSentence",
        jp: "好き",
        furigana: "Suki",
        id: "Suka",
      },
      {
        _key: "ex13",
        _type: "exampleSentence",
        jp: "大変",
        furigana: "Taihen",
        id: "Sulit / Berat",
      },
      {
        _key: "ex14",
        _type: "exampleSentence",
        jp: "有名",
        furigana: "Yuumee",
        id: "Terkenal",
      },
    ],
    quizzes: [
      {
        _key: "q1",
        _type: "quiz",
        question:
          "Mana yang merupakan ciri khas Kata Sifat-Na meskipun berakhiran huruf 'i'?",
        options: [
          { _key: "o1", text: "大きい (Ookii)", isCorrect: false },
          { _key: "o2", text: "きれい (Kirei)", isCorrect: true },
        ],
      },
    ],
  },
];

async function main() {
  const client = getCliClient();
  console.log("🚀 Mengimpor Materi Kosakata Batch 2 (Bab 5-9)...");

  try {
    for (const lesson of vocabLessonsBatch2) {
      await client.createOrReplace(lesson);
      console.log(`✅ Tereksekusi: ${lesson.title}`);
    }
    console.log("🎉 Boom! Semua 9 Modul Kosakata N5 Irodori sudah tayang!");
  } catch (error) {
    console.error("❌ Error:", error);
  }
}

main();
